### ISSUE TITLE
后台管理路径问题

### ISSUE THREAD

**Issue by Wittoy** [walinejs/tcb-starter#3]
基于CloudBase的后台管理中，评论以及个人设置仍指向主域名子目录，而不是子目录 `(/waline)` 后一级。

**Comment by lizheming** [comment]
那个链接需要你确认下你的 `SITE_URL` 环境变量是否有配置子目录？

**Comment by Wittoy** [comment]
原谅我解释问题过于傻逼（
这个模板默认是部署在 `/waline` 目录下，但在后台 `管理 - 评论` 以及 `个人设置` 依旧是这样的指向
![Snipaste_2021-01-31_22-53-00.png](https://7.dusays.com/2021/01/31/54be672063c06.png)
![Snipaste_2021-01-31_22-53-16.png](https://7.dusays.com/2021/01/31/4a640576509f1.png)
以及在Waline窗口中的登录按钮 登录后也出现这种情形![Snipaste_2021-01-31_22-49-22.png](https://7.dusays.com/2021/01/31/7eb9a538d9e98.png)

**Comment by lizheming** [comment]
已经优化了一下，可以再试试。
