### ISSUE TITLE
部署到tcb后，表情乱码

### ISSUE THREAD

**Issue by east4ming** [walinejs/tcb-starter#6]
![image](https://user-images.githubusercontent.com/13358726/128275150-47a90606-688e-474a-b019-eb00c8c2f912.png)
用的是你的demo环境，用自己的cloudbase也是同样的情况

**Comment by lizheming** [comment]
已经将 @waline/cloudbase 同步升级到最新，请更新下依赖再看看

**Comment by east4ming** [comment]
请求ID: b7af6170b00e78ed4040d233fb1219b1
错误码: INVOKE_FUNCTION_FAILED
错误信息: Code: -1 ScfRequestId: ddab1d36-03d2-11ec-a507-e6f017eac8b4 Error: ReferenceError: TextEncoder is not defined at Object.<anonymous> (/var/user/node_modules/whatwg-url/dist/encoding.js:2:21) at Module._compile (internal/modules/cjs/loader.js:701:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) at Module.load (internal/modules/cjs/loader.js:600:32) at tryModuleLoad (internal/modules/cjs/loader.js:539:12) at Function.Module._load (internal/modules/cjs/loader.js:531:3) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:22:18) at Object.<anonymous> (/var/user/node_modules/whatwg-url/dist/url-state-machine.js:5:34) at Module._compile (internal/modules/cjs/loader.js:701:30)

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues/478 看一下这个 issue
